feat(svg): add possibility to display an svg instead of an icon
ovh-ux/ovh-angular-actions-menu pull request #3
Opened 2017-07-06 14:57 UTC by Jisay

2017-07-06 14:57 UTC, antleblanc approved these changes

2017-07-06 15:09 UTC, bnjjj approved these changes

2017-07-07 05:52 UTC, antleblanc requested changes

2017-07-07 05:52 UTC, antleblanc commented on dist/ovh-angular-actions-menu.js
> + *  @param {String} [options.svg] Template cache path of the actions menu item icon.
Could you please re-run a `grunt` command to fix your dist files?
Should be: `SVG code escaped by using $sce.trustAsHtml method.` right?

2017-07-07 06:52 UTC, antleblanc approved these changes

2017-07-07 06:58 UTC, merged